### PR TITLE
GitHub actions

### PR DESCRIPTION
**Pull request by l-hedgehog**
This PR adds a script to download the most recent extension versions directly from taskcluster artifacts, and a Github action to run said script and create regular PRs for each new Firefox versions.

A taskcluster client with scopes `queue:get-artifact:xpi/build/cehomepage.xpi queue:get-artifact:xpi/build/cpmanager.xpi` should be created and its client_id and access_token set as repository secrets in Github.

To run the Github action, one need to manually trigger it with three inputs: Firefox version (for determine whether to base the PR on `master` or `esr` branch, also for commit message and PR branch name), year & month that Fx version is scheduled to be released (for updating the distribution version).

[Demo runs](https://github.com/MozillaOnline/mozillaonline/actions/workflows/create-pr.yml) and [PRs](https://github.com/MozillaOnline/mozillaonline/pulls/app%2Fgithub-actions) are currently available in a forked repo.

Thanks!

### CODE REVIEW

**Comment by mkaply** [comment]
@l-hedgehog I got the approvals I needed to do this and I've setup the secrets in the repo. Do you want to retest then I can approve and we can merge?

**Comment by l-hedgehog** [comment]
> I got the approvals I needed to do this and I've setup the secrets in the repo. Do you want to retest then I can approve and we can merge?

I've rebased the branch and [demo runs](https://github.com/MozillaOnline/mozillaonline/actions/workflows/create-pr.yml) and [PRs](https://github.com/MozillaOnline/mozillaonline/pulls/app%2Fgithub-actions) in the forked repo were also updated.

**Comment by mkaply** [comment]
Looks like everything is working was expected. Should I merge?

**Comment by l-hedgehog** [comment]
> Looks like everything is working was expected. Should I merge?

Yes, please. Thanks!

**Comment by l-hedgehog** [comment]
Hi @mkaply I took the liberty to land the same script on `esr` branch in a5edbf8598fefc37718b7ef1e7246495a915efc7, and created the PRs for Fx 97.0 (#60) & 91.6.0esr (#61) with the action.

**Pull request merged**
